version: "3.3"
services:
  bot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./.env.docker
    volumes:
      - $HOME/.ssh/id_ed25519:/home/docker/.ssh/id_ed25519
