apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP
  labels:
    app: $APP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: $APP
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.0.0.2
      nodeSelector:
        storage: "false"
      containers:
        - name: $APP
          image: $IMAGE
          envFrom:
            - secretRef:
                name: klexhub-phonebot-env
          env:
            - name: SFTP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: sip-klex-ssh-key
                  key: SFTP_PRIVATE_KEY
      imagePullSecrets:
        - name: k8net-registry-secret
